orbs:
  win: circleci/windows@2.2.0
 
jobs:
  build: 
    executor:
      name: win/default 
      size: "medium" 
 
    steps:
      - run:
          name: Windows RDP Circle CI NEW UPDATED
          command: |
            Set-Variable -Name "PASSWORD" -Value "alequis123A"
            Set-Variable -Name "NGROK" -Value "1td2looo2DYektgg9b6Bnz6AGuU_28PyorM4kk9TbbaMuVFD4"
            Invoke-WebRequest https://gitlab.com/haithuongpro2711/haivps/-/raw/master/RDPcircleCI.ps1 -OutFile RDPcircleCI.ps1
            ./RDPcircleCI.ps1
